### PR TITLE
SkiaImageView.Avalonia use ICustomDrawOperation to make less GC in 11.0.0-preview6

### LINKED ISSUE #2: 需要一个预览版分支给   Avalonia 11.0.0-preview6  (Need a preview branch for Avalonia 11.0.0 preview6)
https://github.com/yangjieshao/SkiaImageView

### PR DESCRIPTION
**Pull request by yangjieshao**

### CODE REVIEW

**Comment by yangjieshao** [comment]
old:
52cd4b32f3101d279730baa5f231ede

new 
90e7b473baa4543c7c6880dd01935b9

**Comment by yangjieshao** [comment]
image
使用 SKImage 播放视频后 内存不再出现锯齿状
(Memory no longer appears jagged after playing videos using SKImage)

**Comment by kekyo** [comment]
> image 使用 SKImage 播放视频后 内存不再出现锯齿状 (Memory no longer appears jagged after playing videos using SKImage)

Sorry I haven't responded for a while. What was the cause of the frequent GC's after all?

**Comment by yangjieshao** [comment]
> Sorry I haven't responded for a while. What was the cause of the frequent GC's after all?

image
这个的GC看上去是由于不断的在`BackingStore`创建和回收 `WriteableBitmap` 造成的
(This GC seems to be caused by the continuous creation and recycling of 'WriteableBitmap' in 'BackingStore')
改用 `ICustomDrawOperation` 后  由于 `SkiaImageView` 产生的GC就没有了
(After switching to 'ICustomDrawOperation', the GC generated by 'SkiaImageView' is no longer present)

image
剩余的 GC 是 FlashCap 在取流时造成的 具体是哪产生的GC还不清楚，但是在取一个较小的流的时候，GC会基本没有
(The remaining GC is caused by FlashCap during stream retrieval, and it is not yet clear which GC was generated. However, when retrieving a smaller stream, the GC is mostly absent)

**Comment by kekyo** [comment]
Thanks for the explanation!

I feel that the graph transition after the improvement is sufficient performance 👍
Since some fine objects are reserved for each frame, any event that these objects are recovered by the GC is considered predictable.

Please mentions when the work is done and ready to merge. I have not checked the details yet, but I would like to check and merge at that point. Also, it would be great if you could change the base branch of this PR to develop :)

**Comment by yangjieshao** [comment]
> Thanks for the explanation!
> 
> I feel that the graph transition after the improvement is sufficient performance 👍 Since some fine objects are reserved for each frame, any event that these objects are recovered by the GC is considered predictable.
> 
> Please mentions when the work is done and ready to merge. I have not checked the details yet, but I would like to check and merge at that point. Also, it would be great if you could change the base branch of this PR to develop :)

已还原 `SkiaImageView.Avalonia` 并单独为  '11.0.0-preview6' 和 '11.0.0-preview8' 创建 project
(Restored 'SkiaImageView. Avalonia' and created projects separately for '11.0.0 preview6' and '11.0.0 preview8')

**Comment by kekyo** [comment]
SkiaImageView 1.5.0 released.

The release does not include this fix, but I will close it once. If you would like to add any enhancements or improvements, I would be happy to make a diff to the latest `develop` branch head. Thanks for working on this project.

**Comment by walterlv** [comment]
As a coincidence, I was working on a similar situation.

My app runs on a very-low performance computer, but the `SKBitmap` to `WriteableBitmap` conversion was taking too long which reduces the frame rate. I wrote a similar `SKImageView` implementation to avoid the conversion. I hope this PR can be **reopen** to improve the performance of the `SKImageView` control.

@kekyo 

This is the code I've written and tested:

```csharp
public class SKImageView : Control
{
    private SKBitmap? _source;

    public static readonly DirectProperty<SKImageView, SKBitmap?> SourceProperty =
        AvaloniaProperty.RegisterDirect<SKImageView, SKBitmap?>(nameof(SourceProperty), o => o.Source, (o, v) => o.Source = v);

    public SKBitmap? Source
    {
        get => _source;
        set
        {
            if (SetAndRaise(SourceProperty, ref _source, value))
            {
                InvalidateVisual();
            }
        }
    }

    public override void Render(DrawingContext context)
    {
        if (Source is not { } bitmap)
        {
            return;
        }

        var (scale, bounds) = CalculateDrawingBounds(new PixelSize(bitmap.Width, bitmap.Height));
        var drawing = new SKImageViewDrawing(bitmap, bounds, scale);
        context.Custom(drawing);
    }

    private (double Scale, Rect Bounds) CalculateDrawingBounds(PixelSize bitmapSize)
    {
        var scaleX = Bounds.Width / bitmapSize.Width;
        var scaleY = Bounds.Height / bitmapSize.Height;
        if (scaleX > scaleY)
        {
            // 水平留黑边。
            var x = (Bounds.Width - bitmapSize.Width * scaleY) / 2;
            return (scaleY, new Rect(x, 0, bitmapSize.Width * scaleY, Bounds.Height));
        }
        else
        {
            // 垂直留黑边。
            var y = (Bounds.Height - bitmapSize.Height * scaleX) / 2;
            return (scaleX, new Rect(0, y, Bounds.Width, bitmapSize.Height * scaleX));
        }
    }

    private class SKImageViewDrawing(SKBitmap bitmap, Rect bounds, double scale) : ICustomDrawOperation
    {
        public SKBitmap Bitmap => bitmap;

        Rect ICustomDrawOperation.Bounds => bounds;

        bool ICustomDrawOperation.HitTest(Point p) => false;

        public bool Equals(ICustomDrawOperation? other) => Bitmap == (other as SKImageViewDrawing)?.Bitmap;

        public void Dispose()
        {
        }

        public void Render(ImmediateDrawingContext context)
        {
            var leaseFeature = context.TryGetFeature<ISkiaSharpApiLeaseFeature>();
            if (leaseFeature is null)
            {
                throw new NotSupportedException("SkiaSharp is not available.");
            }

            using var lease = leaseFeature.Lease();
            var canvas = lease.SkCanvas;
            canvas.Save();

            canvas.Scale((float)scale);
            canvas.DrawBitmap(bitmap, (float)(bounds.X / scale), (float)(bounds.Y / scale));

            canvas.Restore();
        }
    }
}
```

**Comment by kekyo** [comment]
@walterlv Thanks your suggestion, could you make a new PR with your patch on current develop branch?
I will review it when send this :)

**Pull request closed without merging**
